# Generated by cpp11: do not edit by hand

cpp_fixed_cost_gaussian_ <- function(n_i, n_cells, index_i, index_j, order, invTableCluster_vector, dum_vector) {
  .Call(`_fixest2_cpp_fixed_cost_gaussian_`, n_i, n_cells, index_i, index_j, order, invTableCluster_vector, dum_vector)
}

update_mu_single_cluster_ <- function(family, nb_cluster, theta, diffMax_NR, mu_in, lhs, sum_y, dum, obsCluster, table, cumtable, nthreads) {
  .Call(`_fixest2_update_mu_single_cluster_`, family, nb_cluster, theta, diffMax_NR, mu_in, lhs, sum_y, dum, obsCluster, table, cumtable, nthreads)
}

get_n_cells_ <- function(index_i, index_j) {
  .Call(`_fixest2_get_n_cells_`, index_i, index_j)
}

cpp_derivconv_seq_gnl_ <- function(iterMax, diffMax, n_vars, nb_cluster_all, ll_d2, jacob_vector, deriv_init_vector, dum_vector) {
  .Call(`_fixest2_cpp_derivconv_seq_gnl_`, iterMax, diffMax, n_vars, nb_cluster_all, ll_d2, jacob_vector, deriv_init_vector, dum_vector)
}

cpp_derivconv_acc_gnl_ <- function(iterMax, diffMax, n_vars, nb_cluster_all, ll_d2, jacob_vector, deriv_init_vector, dum_vector) {
  .Call(`_fixest2_cpp_derivconv_acc_gnl_`, iterMax, diffMax, n_vars, nb_cluster_all, ll_d2, jacob_vector, deriv_init_vector, dum_vector)
}

cpp_derivconv_acc_2_ <- function(iterMax, diffMax, n_vars, nb_cluster_all, n_cells, index_i, index_j, ll_d2, order, jacob_vector, deriv_init_vector, dum_vector) {
  .Call(`_fixest2_cpp_derivconv_acc_2_`, iterMax, diffMax, n_vars, nb_cluster_all, n_cells, index_i, index_j, ll_d2, order, jacob_vector, deriv_init_vector, dum_vector)
}

cpp_derivconv_seq_2_ <- function(iterMax, diffMax, n_vars, nb_cluster_all, n_cells, index_i, index_j, order, ll_d2, jacob_vector, deriv_init_vector, dum_vector) {
  .Call(`_fixest2_cpp_derivconv_seq_2_`, iterMax, diffMax, n_vars, nb_cluster_all, n_cells, index_i, index_j, order, ll_d2, jacob_vector, deriv_init_vector, dum_vector)
}

update_deriv_single_ <- function(n_vars, nb_coef, r_ll_d2, r_jacob_vector, r_dum_vector) {
  .Call(`_fixest2_update_deriv_single_`, n_vars, nb_coef, r_ll_d2, r_jacob_vector, r_dum_vector)
}

cpp_conv_acc_gnl_ <- function(family, iterMax, diffMax, diffMax_NR, theta, nb_cluster_all, lhs, mu_init, dum_vector, tableCluster_vector, sum_y_vector, cumtable_vector, obsCluster_vector, nthreads) {
  .Call(`_fixest2_cpp_conv_acc_gnl_`, family, iterMax, diffMax, diffMax_NR, theta, nb_cluster_all, lhs, mu_init, dum_vector, tableCluster_vector, sum_y_vector, cumtable_vector, obsCluster_vector, nthreads)
}

cpp_conv_seq_gnl_ <- function(family, iterMax, diffMax, diffMax_NR, theta, nb_cluster_all, lhs, mu_init, dum_vector, tableCluster_vector, sum_y_vector, cumtable_vector, obsCluster_vector, nthreads) {
  .Call(`_fixest2_cpp_conv_seq_gnl_`, family, iterMax, diffMax, diffMax_NR, theta, nb_cluster_all, lhs, mu_init, dum_vector, tableCluster_vector, sum_y_vector, cumtable_vector, obsCluster_vector, nthreads)
}

cpp_conv_acc_poi_2_ <- function(n_i, n_j, n_cells, index_i, index_j, dum_vector, sum_y_vector, iterMax, diffMax, exp_mu_in, order) {
  .Call(`_fixest2_cpp_conv_acc_poi_2_`, n_i, n_j, n_cells, index_i, index_j, dum_vector, sum_y_vector, iterMax, diffMax, exp_mu_in, order)
}

cpp_conv_seq_poi_2_ <- function(n_i, n_j, n_cells, index_i, index_j, dum_vector, sum_y_vector, iterMax, diffMax, exp_mu_in, order) {
  .Call(`_fixest2_cpp_conv_seq_poi_2_`, n_i, n_j, n_cells, index_i, index_j, dum_vector, sum_y_vector, iterMax, diffMax, exp_mu_in, order)
}

cpp_conv_acc_gau_2_ <- function(n_i, n_j, n_cells, r_mat_row, r_mat_col, r_mat_value_Ab, r_mat_value_Ba, dum_vector, lhs, invTableCluster_vector, iterMax, diffMax, mu_in) {
  .Call(`_fixest2_cpp_conv_acc_gau_2_`, n_i, n_j, n_cells, r_mat_row, r_mat_col, r_mat_value_Ab, r_mat_value_Ba, dum_vector, lhs, invTableCluster_vector, iterMax, diffMax, mu_in)
}

cpp_conv_seq_gau_2_ <- function(n_i, n_j, n_cells, r_mat_row, r_mat_col, r_mat_value_Ab, r_mat_value_Ba, dum_vector, lhs, invTableCluster_vector, iterMax, diffMax, mu_in) {
  .Call(`_fixest2_cpp_conv_seq_gau_2_`, n_i, n_j, n_cells, r_mat_row, r_mat_col, r_mat_value_Ab, r_mat_value_Ba, dum_vector, lhs, invTableCluster_vector, iterMax, diffMax, mu_in)
}

cpp_which_na_inf_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_which_na_inf_`, x, nthreads)
}

cpp_demean_ <- function(y, X_raw, r_weights, iterMax, diffMax, r_nb_id_Q, fe_id_list, table_id_I, slope_flag_Q, slope_vars_list, r_init, nthreads, algo_extraProj, algo_iter_warmup, algo_iter_projAfterAcc, algo_iter_grandAcc, save_fixef) {
  .Call(`_fixest2_cpp_demean_`, y, X_raw, r_weights, iterMax, diffMax, r_nb_id_Q, fe_id_list, table_id_I, slope_flag_Q, slope_vars_list, r_init, nthreads, algo_extraProj, algo_iter_warmup, algo_iter_projAfterAcc, algo_iter_grandAcc, save_fixef)
}

cpp_dsb_ <- function(Rstr) {
  .Call(`_fixest2_cpp_dsb_`, Rstr)
}

cpp_dsb_full_string_ <- function(Rstr) {
  .Call(`_fixest2_cpp_dsb_full_string_`, Rstr)
}

cpp_dsb_if_extract_ <- function(Rstr) {
  .Call(`_fixest2_cpp_dsb_if_extract_`, Rstr)
}

cpp_paste_conditional_ <- function(x, id, n) {
  .Call(`_fixest2_cpp_paste_conditional_`, x, id, n)
}

cpp_cholesky_ <- function(X, tol, nthreads) {
  .Call(`_fixest2_cpp_cholesky_`, X, tol, nthreads)
}

cpp_sparse_products_ <- function(X, w, y, correct_0w, nthreads) {
  .Call(`_fixest2_cpp_sparse_products_`, X, w, y, correct_0w, nthreads)
}

cpp_crossprod_ <- function(X, w, nthreads) {
  .Call(`_fixest2_cpp_crossprod_`, X, w, nthreads)
}

cpp_mat_reconstruct_ <- function(X, id_excl) {
  .Call(`_fixest2_cpp_mat_reconstruct_`, X, id_excl)
}

cpp_iv_products_ <- function(X, y, Z, u, w, nthreads) {
  .Call(`_fixest2_cpp_iv_products_`, X, y, Z, u, w, nthreads)
}

cpp_iv_product_completion_ <- function(XtX, Xty, X, y, U, w, nthreads) {
  .Call(`_fixest2_cpp_iv_product_completion_`, XtX, Xty, X, y, U, w, nthreads)
}

cpp_iv_resid_ <- function(resid_2nd, coef, resid_1st, is_int, nthreads) {
  .Call(`_fixest2_cpp_iv_resid_`, resid_2nd, coef, resid_1st, is_int, nthreads)
}

cpp_add_commas_ <- function(x, r, whole) {
  .Call(`_fixest2_cpp_add_commas_`, x, r, whole)
}

cpp_find_never_always_treated_ <- function(cohort, period) {
  .Call(`_fixest2_cpp_find_never_always_treated_`, cohort, period)
}

cpp_get_first_item_ <- function(x, n_items) {
  .Call(`_fixest2_cpp_get_first_item_`, x, n_items)
}

cpp_combine_clusters_ <- function(cluster_list, index) {
  .Call(`_fixest2_cpp_combine_clusters_`, cluster_list, index)
}

cpp_cut_ <- function(x_sorted, cut_points, is_included) {
  .Call(`_fixest2_cpp_cut_`, x_sorted, cut_points, is_included)
}

cpp_is_int_ <- function(x) {
  .Call(`_fixest2_cpp_is_int_`, x)
}

cpp_hash_string_ <- function(x) {
  .Call(`_fixest2_cpp_hash_string_`, x)
}

cpp_isConstant_ <- function(x) {
  .Call(`_fixest2_cpp_isConstant_`, x)
}

cpp_any_na_null_ <- function(x) {
  .Call(`_fixest2_cpp_any_na_null_`, x)
}

cpp_find_duplicates_ <- function(id, time) {
  .Call(`_fixest2_cpp_find_duplicates_`, id, time)
}

cpp_check_nested_ <- function(fe_list, cluster_list, fe_sizes, n) {
  .Call(`_fixest2_cpp_check_nested_`, fe_list, cluster_list, fe_sizes, n)
}

cpp_pgcd_ <- function(x) {
  .Call(`_fixest2_cpp_pgcd_`, x)
}

cpp_escape_markup_ <- function(Rstr) {
  .Call(`_fixest2_cpp_escape_markup_`, Rstr)
}

cpp_factor_matrix_ <- function(fact, is_na_all, who_is_dropped, var, col_names) {
  .Call(`_fixest2_cpp_factor_matrix_`, fact, is_na_all, who_is_dropped, var, col_names)
}

cpp_diag_XUtX_ <- function(X, U) {
  .Call(`_fixest2_cpp_diag_XUtX_`, X, U)
}

cpp_partialDerivative_other_ <- function(iterMax, Q, N, epsDeriv, ll_d2, dx_dother, init, dumMat, nbCluster) {
  .Call(`_fixest2_cpp_partialDerivative_other_`, iterMax, Q, N, epsDeriv, ll_d2, dx_dother, init, dumMat, nbCluster)
}

cpp_table_ <- function(Q, dum) {
  .Call(`_fixest2_cpp_table_`, Q, dum)
}

cpp_ssr_null_ <- function(y, w) {
  .Call(`_fixest2_cpp_ssr_null_`, y, w)
}

cpp_ssq_ <- function(x, w) {
  .Call(`_fixest2_cpp_ssq_`, x, w)
}

cpp_constant_dum_ <- function(k, x, dum, only_0) {
  .Call(`_fixest2_cpp_constant_dum_`, k, x, dum, only_0)
}

cpp_tapply_sum_ <- function(Q, x, dum) {
  .Call(`_fixest2_cpp_tapply_sum_`, Q, x, dum)
}

cpp_tapply_vsum_ <- function(Q, x, dum) {
  .Call(`_fixest2_cpp_tapply_vsum_`, Q, x, dum)
}

cpp_lag_obs_ <- function(id, time, nlag) {
  .Call(`_fixest2_cpp_lag_obs_`, id, time, nlag)
}

cpp_get_fe_gnl_ <- function(Q, N, sumFE, dumMat, cluster_sizes, obsCluster) {
  .Call(`_fixest2_cpp_get_fe_gnl_`, Q, N, sumFE, dumMat, cluster_sizes, obsCluster)
}

cpp_quf_gnl_ <- function(x) {
  .Call(`_fixest2_cpp_quf_gnl_`, x)
}

cpp_quf_table_sum_ <- function(x, y, do_sum_y, rm_0, rm_1, rm_single, only_slope, nthreads, do_refactor, r_x_sizes, obs2keep) {
  .Call(`_fixest2_cpp_quf_table_sum_`, x, y, do_sum_y, rm_0, rm_1, rm_single, only_slope, nthreads, do_refactor, r_x_sizes, obs2keep)
}

cpp_get_nb_threads_ <- function() {
  .Call(`_fixest2_cpp_get_nb_threads_`)
}

cpp_which_na_inf_vec_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_which_na_inf_vec_`, x, nthreads)
}

cpp_which_na_inf_mat_ <- function(mat, nthreads) {
  .Call(`_fixest2_cpp_which_na_inf_mat_`, mat, nthreads)
}

cpp_which_na_inf_df_ <- function(df, nthreads) {
  .Call(`_fixest2_cpp_which_na_inf_df_`, df, nthreads)
}

cpp_check_only_0_ <- function(x_mat, nthreads) {
  .Call(`_fixest2_cpp_check_only_0_`, x_mat, nthreads)
}

cpp_exp_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_exp_`, x, nthreads)
}

cpp_log_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_log_`, x, nthreads)
}

cpp_log_a_exp_ <- function(a, mu, exp_mu, nthreads) {
  .Call(`_fixest2_cpp_log_a_exp_`, a, mu, exp_mu, nthreads)
}

cpp_cond_means_ <- function(mat_vars, treat, nthreads) {
  .Call(`_fixest2_cpp_cond_means_`, mat_vars, treat, nthreads)
}

cpp_lgamma_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_lgamma_`, x, nthreads)
}

cpp_digamma_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_digamma_`, x, nthreads)
}

cpp_trigamma_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_trigamma_`, x, nthreads)
}

cpp_poisson_linkinv_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_poisson_linkinv_`, x, nthreads)
}

cpp_poisson_validmu_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_poisson_validmu_`, x, nthreads)
}

cpp_logit_linkfun_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_logit_linkfun_`, x, nthreads)
}

cpp_logit_linkinv_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_logit_linkinv_`, x, nthreads)
}

cpp_logit_mueta_ <- function(x, nthreads) {
  .Call(`_fixest2_cpp_logit_mueta_`, x, nthreads)
}

cpp_logit_devresids_ <- function(y, mu, wt, nthreads) {
  .Call(`_fixest2_cpp_logit_devresids_`, y, mu, wt, nthreads)
}

cpp_xwy_ <- function(X, y, w, nthreads) {
  .Call(`_fixest2_cpp_xwy_`, X, y, w, nthreads)
}

cpp_xbeta_ <- function(X, beta, nthreads) {
  .Call(`_fixest2_cpp_xbeta_`, X, beta, nthreads)
}

cpp_matprod_ <- function(x, y, nthreads) {
  .Call(`_fixest2_cpp_matprod_`, x, y, nthreads)
}

cpp_colon_to_star_ <- function(Rstr) {
  .Call(`_fixest2_cpp_colon_to_star_`, Rstr)
}

cpp_newey_west_ <- function(S, w, nthreads) {
  .Call(`_fixest2_cpp_newey_west_`, S, w, nthreads)
}

cpp_newey_west_panel_ <- function(S, w, unit, G, time, time_len, nthreads) {
  .Call(`_fixest2_cpp_newey_west_panel_`, S, w, unit, G, time, time_len, nthreads)
}

cpp_driscoll_kraay_ <- function(S, w, time, time_len, nthreads) {
  .Call(`_fixest2_cpp_driscoll_kraay_`, S, w, time, time_len, nthreads)
}

cpp_vcov_conley_ <- function(S, lon_rad, lat_rad, distance, cutoff, nthreads) {
  .Call(`_fixest2_cpp_vcov_conley_`, S, lon_rad, lat_rad, distance, cutoff, nthreads)
}
